In [1]:
##### This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Stock Split and Dividends by YFinance
These type of data can also be fetched using yfinance library by setting actions argument true<br><br>
**actions: bool**
* Download dividend + stock splits data. Default is False

In [2]:
#installing the library
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.31-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 2.3 MB/s
Collecting pytz>=2022.5
  Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
     |████████████████████████████████| 502 kB 16.6 MB/s
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.8-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (101 kB)
     |████████████████████████████████| 101 kB 7.7 MB/s
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     |████████████████████████████████| 142 kB 69.6 MB/s
Collecting lxml>=4.9.1
  Downloading lxml-4.9.3-cp37-cp37m-manylinux_2_28_x86_64.whl (7.4 MB)
     |████████████████████████████████| 7.4 MB 40.2 MB/s
Collecting requests>=2.31
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 760 kB/s
Requirement already satisfied: numpy>=1.16.5 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.20.3)
Requirement already satisfied: html5lib>=1.1 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.1)
Requirement already satisfied: pandas>=1.3.0 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.3.5)
Collecting peewee>=3.16.2
  Downloading peewee-3.17.0.tar.gz (2.9 MB)
     |████████████████████████████████| 2.9 MB 58.1 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: appdirs>=1.4.4 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.7/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.1)
Requirement already satisfied: six>=1.9 in /opt/conda/lib/python3.7/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.7/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.31->yfinance) (3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.31->yfinance) (2.0.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.31->yfinance) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.31->yfinance) (2021.10.8)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.0-py3-none-any.whl size=135720 sha256=6f126d548b1fb4a7051d90e5914f780e3bb82ae40b78c51321c6f6d1fdad1c87
  Stored in directory: /root/.cache/pip/wheels/c2/ce/84/33a31720d239d310cfff49d7bf56da412b6caefec2e112f327
Successfully built peewee
Installing collected packages: pytz, requests, peewee, multitasking, lxml, frozendict, beautifulsoup4, yfinance
  Attempting uninstall: pytz
    Found existing installation: pytz 2021.3
    Uninstalling pytz-2021.3:
      Successfully uninstalled pytz-2021.3
  Attempting uninstall: requests
    Found existing installation: requests 2.26.0
    Uninstalling requests-2.26.0:
      Successfully uninstalled requests-2.26.0
  Attempting uninstall: lxml
    Found existing installation: lxml 4.8.0
    Uninstalling lxml-4.8.0:
      Successfully uninstalled lxml-4.8.0
  Attempting uninstall: frozendict
    Found existing installation: frozendict 2.3.0
    Uninstalling frozendict-2.3.0:
      Successfully uninstalled frozendict-2.3.0
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.10.0
    Uninstalling beautifulsoup4-4.10.0:
      Successfully uninstalled beautifulsoup4-4.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
explainable-ai-sdk 1.3.2 requires xai-image-widget, which is not installed.
beatrix-jupyterlab 3.1.6 requires google-cloud-bigquery-storage, which is not installed.
spacy 3.2.3 requires typing-extensions<4.0.0.0,>=3.7.4; python_version < "3.8", but you have typing-extensions 4.1.1 which is incompatible.
gcsfs 2021.11.1 requires fsspec==2021.11.1, but you have fsspec 2022.2.0 which is incompatible.
featuretools 1.6.0 requires numpy>=1.21.0, but you have numpy 1.20.3 which is incompatible.
arviz 0.11.4 requires typing-extensions<4,>=3.7.4.3, but you have typing-extensions 4.1.1 which is incompatible.
apache-beam 2.34.0 requires dill<0.3.2,>=0.3.1.1, but you have dill 0.3.4 which is incompatible.
apache-beam 2.34.0 requires httplib2<0.20.0,>=0.8, but you have httplib2 0.20.2 which is incompatible.
apache-beam 2.34.0 requires pyarrow<6.0.0,>=0.15.1, but you have pyarrow 6.0.1 which is incompatible.
apache-beam 2.34.0 requires typing-extensions<4,>=3.7.0, but you have typing-extensions 4.1.1 which is incompatible.
Successfully installed beautifulsoup4-4.12.2 frozendict-2.3.8 lxml-4.9.3 multitasking-0.0.11 peewee-3.17.0 pytz-2023.3.post1 requests-2.31.0 yfinance-0.2.31
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [3]:
#importing the library in the environment
import yfinance as yf

In [4]:
#setting the ticker
ticker="aapl"

In [5]:
#creating a dataframe by fetching the data 
df=yf.download(ticker,period="10y",actions=True)

[*********************100%%**********************]  1 of 1 completed

In [6]:
#checking the dataframe
df

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2013-10-21,18.277500,18.725000,18.268572,18.620001,16.250626,398106800,0.0,0.0
2013-10-22,18.800358,18.873215,18.143929,18.566786,16.204185,534063600,0.0,0.0
2013-10-23,18.535713,18.773930,18.535713,18.748571,16.362837,313723200,0.0,0.0
2013-10-24,18.750000,19.016787,18.658930,18.996786,16.579458,384764800,0.0,0.0
2013-10-25,18.975714,19.043928,18.753929,18.784286,16.394007,337792000,0.0,0.0
...,...,...,...,...,...,...,...,...
2023-10-16,176.750000,179.080002,176.509995,178.720001,178.720001,52517000,0.0,0.0
2023-10-17,176.649994,178.419998,174.800003,177.149994,177.149994,57549400,0.0,0.0
2023-10-18,175.580002,177.580002,175.110001,175.839996,175.839996,54764400,0.0,0.0
2023-10-19,176.039993,177.839996,175.190002,175.460007,175.460007,59302900,0.0,0.0
2023-10-20,175.309998,175.419998,172.639999,172.880005,172.880005,64189300,0.0,0.0

In [7]:
#checking the info
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2518 entries, 2013-10-21 to 2023-10-20
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          2518 non-null   float64
 1   High          2518 non-null   float64
 2   Low           2518 non-null   float64
 3   Close         2518 non-null   float64
 4   Adj Close     2518 non-null   float64
 5   Volume        2518 non-null   int64
 6   Dividends     2518 non-null   float64
 7   Stock Splits  2518 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 177.0 KB

In [8]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Dividends',
       'Stock Splits'],
      dtype='object')

In [9]:
#producing a dataframe with dividend values of more than 0
df[df.Dividends>0]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2013-11-06,18.719643,18.745001,18.507143,18.604286,16.331707,223375600,0.108929,0.0
2014-02-06,18.216429,18.339287,18.136070,18.303928,16.164221,257765200,0.108929,0.0
2014-05-08,21.008928,21.228930,20.942858,20.999643,18.648392,230297200,0.117500,0.0
2014-08-07,23.732500,23.987499,23.525000,23.620001,21.079691,186844000,0.117500,0.0
2014-11-06,27.150000,27.197500,26.950001,27.174999,24.357513,139874000,0.117500,0.0
2015-02-05,30.004999,30.057501,29.812500,29.985001,26.982244,168984800,0.117500,0.0
2015-05-07,31.192499,31.520000,31.004999,31.315001,28.296757,175763600,0.130000,0.0
2015-08-06,28.992500,29.125000,28.530001,28.782499,26.126074,211612000,0.130000,0.0
2015-11-05,30.462500,30.672501,30.045000,30.230000,27.557436,158210800,0.130000,0.0
2016-02-04,23.965000,24.332500,23.797501,24.150000,22.134411,185886800,0.130000,0.0
2016-05-05,23.500000,23.517500,23.170000,23.309999,21.494600,143562000,0.142500,0.0
2016-08-04,26.395000,26.500000,26.320000,26.467501,24.538404,109634800,0.142500,0.0
2016-11-03,27.745001,27.865000,27.387501,27.457500,25.586948,107730400,0.142500,0.0
2017-02-09,32.912498,33.112499,32.779999,33.105000,30.983458,113399600,0.142500,0.0
2017-05-11,38.112499,38.517502,38.077499,38.487499,36.169701,109020400,0.157500,0.0
2017-08-10,39.974998,40.000000,38.657501,38.830002,36.634880,163217200,0.157500,0.0
2017-11-10,43.777500,43.845001,43.567501,43.667500,41.347015,100582000,0.157500,0.0
2018-02-09,39.267502,39.472500,37.560001,39.102501,37.175549,282690400,0.157500,0.0
2018-05-11,47.372501,47.514999,46.862499,47.147499,44.996937,104848800,0.182500,0.0
2018-08-10,51.840000,52.275002,51.667500,51.882500,49.689625,98444800,0.182500,0.0
2018-11-08,52.494999,52.529999,51.687500,52.122501,50.093658,101450400,0.182500,0.0
2019-02-08,42.247501,42.665001,42.105000,42.602501,41.119816,95280000,0.182500,0.0
2019-05-10,49.355000,49.712502,48.192501,49.294998,47.762619,164834800,0.192500,0.0
2019-08-09,50.325001,50.689999,49.822498,50.247501,48.870499,98478800,0.192500,0.0
2019-11-07,64.684998,65.087502,64.527496,64.857498,63.269493,94940400,0.192500,0.0
2020-02-07,80.592499,80.849998,79.500000,80.007500,78.233780,117684000,0.192500,0.0
2020-05-08,76.410004,77.587502,76.072502,77.532501,76.018883,133838400,0.205000,0.0
2020-08-07,113.205002,113.675003,110.292503,111.112503,109.139755,198045600,0.205000,0.0
2020-11-06,118.320000,119.199997,116.129997,118.690002,116.783867,114457900,0.205000,0.0
2021-02-05,137.350006,137.419998,135.860001,136.759995,134.764725,75693800,0.205000,0.0
2021-05-07,130.850006,131.259995,129.479996,130.210007,128.528244,78973300,0.220000,0.0
2021-08-06,146.350006,147.110001,145.630005,146.139999,144.468628,54126800,0.220000,0.0
2021-11-05,151.889999,152.199997,150.059998,151.279999,149.768097,65463900,0.220000,0.0
2022-02-04,171.679993,174.100006,170.679993,172.389999,170.884567,82465400,0.220000,0.0
2022-05-06,156.009995,159.440002,154.179993,157.279999,156.135574,116124600,0.230000,0.0
2022-08-05,163.210007,165.850006,163.000000,165.350006,164.374878,56697000,0.230000,0.0
2022-11-04,142.089996,142.669998,134.380005,138.380005,137.792114,140814800,0.230000,0.0
2023-02-10,149.460007,151.339996,149.220001,151.009995,150.598038,57450700,0.230000,0.0
2023-05-12,173.619995,174.059998,171.000000,172.570007,172.337280,45497800,0.240000,0.0
2023-08-11,177.320007,178.619995,176.550003,177.789993,177.789993,51988100,0.240000,0.0

In [14]:
#checking the data of specific range 
df.loc["2013-11-05":"2013-11-15"]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2013-11-05,18.735001,18.888929,18.678572,18.766071,16.378101,265213200,0.000000,0.0
2013-11-06,18.719643,18.745001,18.507143,18.604286,16.331707,223375600,0.108929,0.0
2013-11-07,18.556429,18.685356,18.299286,18.303213,16.067411,262620400,0.000000,0.0
2013-11-08,18.377857,18.611786,18.306786,18.591429,16.320421,279316800,0.000000,0.0
2013-11-11,18.571072,18.631071,18.371786,18.537500,16.273087,227452400,0.000000,0.0
2013-11-12,18.488214,18.711430,18.464287,18.571787,16.303185,204276800,0.000000,0.0
2013-11-13,18.500000,18.651787,18.462856,18.593929,16.322620,197220800,0.000000,0.0
2013-11-14,18.671785,18.902857,18.638214,18.862858,16.558695,282419200,0.000000,0.0
2013-11-15,18.806429,18.896070,18.731787,18.749643,16.459311,317920400,0.000000,0.0

In [15]:
df.loc["2013-11-05":"2013-11-15"].diff()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2013-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-11-06,-0.015358,-0.143929,-0.171429,-0.161785,-0.046394,-41837600.0,0.108929,0.0
2013-11-07,-0.163214,-0.059645,-0.207857,-0.301073,-0.264296,39244800.0,-0.108929,0.0
2013-11-08,-0.178572,-0.073570,0.007500,0.288216,0.253010,16696400.0,0.000000,0.0
2013-11-11,0.193214,0.019285,0.065001,-0.053928,-0.047335,-51864400.0,0.000000,0.0
2013-11-12,-0.082857,0.080359,0.092501,0.034286,0.030098,-23175600.0,0.000000,0.0
2013-11-13,0.011786,-0.059643,-0.001431,0.022142,0.019436,-7056000.0,0.000000,0.0
2013-11-14,0.171785,0.251070,0.175358,0.268929,0.236074,85198400.0,0.000000,0.0
2013-11-15,0.134644,-0.006786,0.093573,-0.113214,-0.099384,35501200.0,0.000000,0.0

In [18]:
df.loc["2014-06-05":"2014-06-15"]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2014-06-05,23.078571,23.191786,22.950357,23.119642,20.531019,303805600,0.0,0.0
2014-06-06,23.210714,23.259287,23.016787,23.056070,20.474560,349938400,0.0,0.0
2014-06-09,23.174999,23.469999,22.937500,23.424999,20.802197,301660000,0.0,7.0
2014-06-10,23.682501,23.762501,23.392500,23.562500,20.924292,251108000,0.0,0.0
2014-06-11,23.532499,23.690001,23.367500,23.465000,20.837711,182724000,0.0,0.0
2014-06-12,23.510000,23.530001,22.975000,23.072500,20.489153,218996000,0.0,0.0
2014-06-13,23.049999,23.110001,22.719999,22.820000,20.264927,218100000,0.0,0.0

In [16]:
#producing a dataframe with stock splits values of more than 0
df[df["Stock Splits"]>0]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2014-06-09,23.174999,23.469999,22.9375,23.424999,20.802197,301660000,0.0,7.0
2020-08-31,127.580002,131.000000,126.0000,129.039993,126.748947,225702700,0.0,4.0