### **Pandas**

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool

In [9]:
# Importing pandas
import pandas as pd

# pd.option.display.max_rows
pd.options.display.max_rows = 60


# pd.options.display.min_rows
pd.options.display.min_rows = None

In [10]:
# Read RELIANCE data that we have downloaded
# Read a csv file
df = pd.read_csv("/content/drive/MyDrive/Project/Practice set/RELIANCE.NS.csv")

In [11]:
# Print the DataFrame
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2022-09-05,2531.000000,2581.500000,2531.000000,2569.800049,2560.754395,5227785
1,2022-09-06,2573.000000,2606.000000,2572.000000,2596.850098,2587.709229,5030172
2,2022-09-07,2575.000000,2594.899902,2570.000000,2581.750000,2572.662109,3455942
3,2022-09-08,2588.250000,2598.000000,2571.000000,2585.399902,2576.299316,3256840
4,2022-09-09,2610.000000,2610.000000,2564.000000,2569.300049,2560.256104,3837302
5,2022-09-12,2570.550049,2612.000000,2570.550049,2598.050049,2588.904785,3431445
6,2022-09-13,2618.000000,2629.699951,2601.000000,2619.750000,2610.528564,4102114
7,2022-09-14,2575.000000,2610.000000,2572.750000,2588.350098,2579.239014,4004997
8,2022-09-15,2583.000000,2603.550049,2556.750000,2562.699951,2553.679199,4783723
9,2022-09-16,2543.750000,2553.000000,2491.000000,2499.199951,2490.402832,9330469
10,2022-09-19,2499.199951,2522.699951,2481.350098,2502.449951,2493.641357,3498286
11,2022-09-20,2522.449951,2537.699951,2494.699951,2502.850098,2494.040039,3881882
12,2022-09-21,2496.750000,2533.000000,2495.000000,2509.750000,2500.915771,4249172
13,2022-09-22,2486.000000,2503.000000,2472.100098,2486.100098,2477.348877,4757219
14,2022-09-23,2485.000000,2495.949951,2436.100098,2439.500000,2430.912842,4397194
15,2022-09-26,2394.050049,2417.800049,2375.149902,2377.350098,2368.981689,5759298
16,2022-09-27,2394.000000,2426.000000,2360.100098,2396.250000,2387.815186,7455448
17,2022-09-28,2360.350098,2378.000000,2327.100098,2332.449951,2324.239746,7844140
18,2022-09-29,2360.000000,2367.500000,2313.000000,2325.300049,2317.114990,6771046
19,2022-09-30,2311.000000,2402.000000,2311.000000,2377.750000,2369.380371,8589908
20,2022-10-03,2391.500000,2416.949951,2363.000000,2369.500000,2361.159424,5470030
21,2022-10-04,2397.800049,2418.000000,2390.149902,2413.199951,2404.705566,4129893
22,2022-10-06,2429.000000,2450.000000,2418.149902,2422.100098,2413.574219,6162021
23,2022-10-07,2414.649902,2443.899902,2414.649902,2432.350098,2423.788086,3560167
24,2022-10-10,2405.000000,2417.600098,2388.000000,2405.800049,2397.331543,2921076
25,2022-10-11,2414.000000,2414.000000,2351.100098,2357.899902,2349.600098,4252803
26,2022-10-12,2352.000000,2381.699951,2343.100098,2375.250000,2366.889160,3422992
27,2022-10-13,2371.399902,2394.000000,2360.100098,2382.800049,2374.412598,3382098
28,2022-10-14,2415.000000,2416.350098,2369.100098,2370.699951,2362.354980,4202459
29,2022-10-17,2355.000000,2414.000000,2343.600098,2408.750000,2400.271240,7720595
...,...,...,...,...,...,...,...
219,2023-07-24,2481.000000,2514.949951,2469.300049,2487.399902,2478.644287,11863933
220,2023-07-25,2494.000000,2505.199951,2480.000000,2485.800049,2477.050049,6013010
221,2023-07-26,2485.000000,2547.000000,2485.000000,2526.199951,2517.307617,6455506
222,2023-07-27,2534.050049,2537.649902,2490.350098,2502.699951,2493.890381,8613449
223,2023-07-28,2512.050049,2542.850098,2500.550049,2527.850098,2518.952148,10413926
224,2023-07-31,2527.850098,2553.899902,2517.949951,2549.250000,2540.276611,4275587
225,2023-08-01,2555.000000,2559.000000,2505.300049,2513.199951,2504.353516,4768316
226,2023-08-02,2509.199951,2512.000000,2463.600098,2486.350098,2477.598145,6374107
227,2023-08-03,2475.300049,2500.899902,2458.050049,2475.899902,2467.184814,5084175
228,2023-08-04,2498.800049,2516.000000,2471.600098,2509.550049,2500.716309,11442805
229,2023-08-07,2521.000000,2528.399902,2505.000000,2523.850098,2514.966064,2991435
230,2023-08-08,2528.000000,2534.449951,2499.550049,2508.649902,2499.819336,4922036
231,2023-08-09,2504.850098,2529.000000,2481.100098,2525.199951,2516.311279,5743293
232,2023-08-10,2524.949951,2550.000000,2508.449951,2536.449951,2527.521729,7735299
233,2023-08-11,2532.449951,2558.850098,2512.350098,2547.149902,2538.183838,11089665
234,2023-08-14,2539.000000,2582.300049,2525.000000,2577.250000,2568.177979,4787906
235,2023-08-16,2551.000000,2582.800049,2551.000000,2575.149902,2566.085449,5101556
236,2023-08-17,2567.100098,2578.100098,2532.850098,2538.000000,2529.066162,6836872
237,2023-08-18,2531.250000,2577.600098,2508.550049,2556.800049,2547.800049,9319989
238,2023-08-21,2539.949951,2555.449951,2515.649902,2520.000000,2520.000000,4610873
239,2023-08-22,2516.899902,2537.949951,2499.000000,2519.399902,2519.399902,3856522
240,2023-08-23,2524.199951,2542.850098,2516.949951,2522.199951,2522.199951,4758976
241,2023-08-24,2539.899902,2539.899902,2471.000000,2479.800049,2479.800049,7070010
242,2023-08-25,2456.000000,2505.000000,2442.600098,2468.350098,2468.350098,11111200
243,2023-08-28,2472.000000,2484.000000,2431.100098,2443.750000,2443.750000,6290413
244,2023-08-29,2452.050049,2453.449951,2408.149902,2420.350098,2420.350098,8438322
245,2023-08-30,2432.000000,2443.000000,2415.000000,2418.050049,2418.050049,6084473
246,2023-08-31,2423.000000,2425.000000,2399.899902,2407.000000,2407.000000,10819300
247,2023-09-01,2406.550049,2425.649902,2401.649902,2412.649902,2412.649902,9056421
248,2023-09-04,2412.649902,2423.649902,2405.300049,2410.699951,2410.699951,4671325

### *   Understanding Rows, Columns, Slice/Subset, Elements.
### *   Row index name, row index and labels.
### *   Columns and Column Index.

In [4]:
# Getting the head of the dataset
df.head()

         Date     Open         High     Low        Close    Adj Close   Volume
0  2022-09-05  2531.00  2581.500000  2531.0  2569.800049  2560.754395  5227785
1  2022-09-06  2573.00  2606.000000  2572.0  2596.850098  2587.709229  5030172
2  2022-09-07  2575.00  2594.899902  2570.0  2581.750000  2572.662109  3455942
3  2022-09-08  2588.25  2598.000000  2571.0  2585.399902  2576.299316  3256840
4  2022-09-09  2610.00  2610.000000  2564.0  2569.300049  2560.256104  3837302

In [12]:
df.head(15)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2022-09-05,2531.000000,2581.500000,2531.000000,2569.800049,2560.754395,5227785
1,2022-09-06,2573.000000,2606.000000,2572.000000,2596.850098,2587.709229,5030172
2,2022-09-07,2575.000000,2594.899902,2570.000000,2581.750000,2572.662109,3455942
3,2022-09-08,2588.250000,2598.000000,2571.000000,2585.399902,2576.299316,3256840
4,2022-09-09,2610.000000,2610.000000,2564.000000,2569.300049,2560.256104,3837302
5,2022-09-12,2570.550049,2612.000000,2570.550049,2598.050049,2588.904785,3431445
6,2022-09-13,2618.000000,2629.699951,2601.000000,2619.750000,2610.528564,4102114
7,2022-09-14,2575.000000,2610.000000,2572.750000,2588.350098,2579.239014,4004997
8,2022-09-15,2583.000000,2603.550049,2556.750000,2562.699951,2553.679199,4783723
9,2022-09-16,2543.750000,2553.000000,2491.000000,2499.199951,2490.402832,9330469
10,2022-09-19,2499.199951,2522.699951,2481.350098,2502.449951,2493.641357,3498286
11,2022-09-20,2522.449951,2537.699951,2494.699951,2502.850098,2494.040039,3881882
12,2022-09-21,2496.750000,2533.000000,2495.000000,2509.750000,2500.915771,4249172
13,2022-09-22,2486.000000,2503.000000,2472.100098,2486.100098,2477.348877,4757219
14,2022-09-23,2485.000000,2495.949951,2436.100098,2439.500000,2430.912842,4397194

In [13]:
# Getting the tail of the dataset
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
244,2023-08-29,2452.050049,2453.449951,2408.149902,2420.350098,2420.350098,8438322
245,2023-08-30,2432.000000,2443.000000,2415.000000,2418.050049,2418.050049,6084473
246,2023-08-31,2423.000000,2425.000000,2399.899902,2407.000000,2407.000000,10819300
247,2023-09-01,2406.550049,2425.649902,2401.649902,2412.649902,2412.649902,9056421
248,2023-09-04,2412.649902,2423.649902,2405.300049,2410.699951,2410.699951,4671325

In [14]:
df.tail(15)

,Date,Open,High,Low,Close,Adj Close,Volume
234,2023-08-14,2539.000000,2582.300049,2525.000000,2577.250000,2568.177979,4787906
235,2023-08-16,2551.000000,2582.800049,2551.000000,2575.149902,2566.085449,5101556
236,2023-08-17,2567.100098,2578.100098,2532.850098,2538.000000,2529.066162,6836872
237,2023-08-18,2531.250000,2577.600098,2508.550049,2556.800049,2547.800049,9319989
238,2023-08-21,2539.949951,2555.449951,2515.649902,2520.000000,2520.000000,4610873
239,2023-08-22,2516.899902,2537.949951,2499.000000,2519.399902,2519.399902,3856522
240,2023-08-23,2524.199951,2542.850098,2516.949951,2522.199951,2522.199951,4758976
241,2023-08-24,2539.899902,2539.899902,2471.000000,2479.800049,2479.800049,7070010
242,2023-08-25,2456.000000,2505.000000,2442.600098,2468.350098,2468.350098,11111200
243,2023-08-28,2472.000000,2484.000000,2431.100098,2443.750000,2443.750000,6290413
244,2023-08-29,2452.050049,2453.449951,2408.149902,2420.350098,2420.350098,8438322
245,2023-08-30,2432.000000,2443.000000,2415.000000,2418.050049,2418.050049,6084473
246,2023-08-31,2423.000000,2425.000000,2399.899902,2407.000000,2407.000000,10819300
247,2023-09-01,2406.550049,2425.649902,2401.649902,2412.649902,2412.649902,9056421
248,2023-09-04,2412.649902,2423.649902,2405.300049,2410.699951,2410.699951,4671325

### **Characterstics/features and their datatypes (dtypes)**

In [7]:
df.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [15]:
# Dataframe.columns get to know about the columns
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [16]:
# dataframe.index get to know more about the index
df.index

RangeIndex(start=0, stop=249, step=1)

In [17]:
# dataframe.info() know the essential information of your dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       249 non-null    object
 1   Open       249 non-null    float64
 2   High       249 non-null    float64
 3   Low        249 non-null    float64
 4   Close      249 non-null    float64
 5   Adj Close  249 non-null    float64
 6   Volume     249 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 13.7+ KB

In [18]:
# dataframe.shape get to know about the shape of your dataframe
df.shape

(249, 7)

In [19]:
# dataframe.decribe() the stats of your datafrane
df.describe()

,Open,High,Low,Close,Adj Close,Volume
count,249.000000,249.000000,249.000000,249.000000,249.000000,2.490000e+02
mean,2484.244974,2503.836736,2461.842782,2482.195390,2473.840035,5.961901e+06
std,117.663758,119.724560,118.200098,120.514881,120.024943,2.919678e+06
min,2215.000000,2220.000000,2180.000000,2201.250000,2193.501465,0.000000e+00
25%,2400.000000,2417.800049,2373.000000,2385.399902,2377.003174,3.985159e+06
50%,2489.899902,2508.550049,2467.000000,2485.800049,2477.348877,5.190958e+06
75%,2557.000000,2582.300049,2541.100098,2557.100098,2548.099121,6.985001e+06
max,2830.000000,2856.000000,2797.000000,2841.850098,2831.846680,1.935881e+07